### ISSUE TITLE
Callback endpoint error

### ISSUE THREAD

**Issue by nbertollo** [klausbetz/apple-identity-provider-keycloak#15]
Hi Klaus,

i got this errore using the identity provider:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/119128593/204101858-24585026-2e47-44a5-8846-50bbc88e8421.png">

I'm using Keycloak 20.0.1 on docker.

TIA.
Nicola Bertollo

**Comment by klausbetz** [comment]
@nbertollo: thx for reporting this bug!

Should be fixed in `1.3.0`
