### ISSUE TITLE
Keycloak Events

### ISSUE THREAD

**Issue by laurocesar** [klausbetz/apple-identity-provider-keycloak#24]
Is there a way to enable Keycloak Events for this plugin?

There are several standard events with the preflix "Identity provider", but I noticed that they are not recorded.

**Comment by klausbetz** [comment]
I'll check that for you. Sounds interesting.

But it may take some time, as i've not to much time till the end of this year.

**Comment by klausbetz** [comment]
I did some research and had a look on the source code of several other baked-in Identity providers from Keycloak.

The Apple-IDP look almost identical (at least from the event perspective) to many other IDPs. It also uses the same base implementation `OIDCIdentityProvider` as e.g. google which takes care of most events.

I assume you are talking about this screen where you can configure login events to be saved for a certain period of time?
<img width="1402" alt="Bildschirm­foto 2023-01-20 um 13 05 13" src="https://user-images.githubusercontent.com/78362353/213691397-859b4e32-9f5b-4781-9565-209b68a88a78.png">

I gave it a test using this Apple IDP and the standard Google IDP from Keycloak.
Both do not spit out any identity_provider event in the event list.

Not sure how to proceed here?

**Comment by klausbetz** [comment]
@laurocesar Is this still relevant for you?

**Comment by laurocesar** [comment]
I checked that everything looks fine now:

<img width="284" alt="image" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/297989/0e958af3-96ce-4eae-a1ae-72b7ab831d53">
