### ISSUE TITLE
keycloak v19.0.3

### ISSUE THREAD

**Issue by OlivAnno** [klausbetz/apple-identity-provider-keycloak#26]
Probleme de compatibilité entre keycloak et votre plugin 
Message apres indentification
« Erreur inattendue lors de l’authentification avec le fournisseur identifié » 

Nous utilisons la solution IAM Keycloak (https://www.keycloak.org/), version 19.0.3, pour la gestion du compte
et avons intégré le SDK openid / AppAuth-iOS (https://github.com/openid/AppAuth-iOS) sur l'application pour le connecter à Keycloak.
Nous voulons savoir Comment intégrer Apple signin à Keycloak ?

**Comment by klausbetz** [comment]
Hi @OlivAnno!

I did my best to understand your request.
As french is not really my mother tongue, I used [deepl](https://www.deepl.com) to translate your issue and I think it did a good job.

So, you're at `19.0.3` and this extension throws an error.  
It would be interesting which version you are using of this extension.  
[1.2.0](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.2.0) should be compatible to Keycloak `19.0.3`.

Please let me know if version `1.2.0` fixed your issue or you're still stuck. Logs from Keycloak when the error occurred would be helpful as well.

**Comment by daviddelannoy** [comment]
Hi, 
I can confirm that it works fine with 19.0.3 and release 1.2.0
