### ISSUE TITLE
Apple button text

### ISSUE THREAD

**Issue by pckhoi** [klausbetz/apple-identity-provider-keycloak#34]
According to [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/technologies/sign-in-with-apple/#creating-a-custom-sign-in-with-apple-button) the button should be titled with only _Sign in with Apple_, _Sign up with Apple_, or _Continue with Apple_.

Overriding `getDisplayName` within `AppleIdentityProviderConfig` seems to do the trick:

```java
# AppleIdentityProviderConfig.java

    @Override
    public String getDisplayName() {
        return "Sign in with Apple";
    }
```

Perhaps this text could be configurable similar to team id. Would you be interested in a PR to that effect?

**Comment by klausbetz** [comment]
Hi @pckhoi 😀 

Thx for reaching out to me.  
Yeah. Human Interface Guidelines. This is kinda tricky.  
Even though changing the `DisplayName` is easy and effective, the button on the login screen of the standard theme would still not comply to Apple's Guidelines (wrong padding, font height, basically the whole button styling).

I'd recommend handling the guidelines in your own login theme, as you have full control over the `DisplayName` (even with different locales) and styles.

Unfortunately, within this extension it's not possible to change any styling for the login theme (except the font-awesome icon).
