### ISSUE TITLE
Missing tooltips and labels in version 1.2.0 (Keycloak version 17.0.1)

### ISSUE THREAD

**Issue by robertsv** [klausbetz/apple-identity-provider-keycloak#48]
It seems that labels and tooltips are missing in version 1.2.0 (Keycloak version 17.0.1).

![2023-08-07 13_39_09-Firefox Developer Edition](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/2462910/e1adbe15-1efa-45c0-b3fa-a19aa81c1493)

**Comment by klausbetz** [comment]
Hi @robertsv,

Any chance you can upgrade your Keycloak instance to v20 or later?

**Comment by robertsv** [comment]
> Any chance you can upgrade your Keycloak instance to v20 or later?

No.

**Comment by klausbetz** [comment]
As long as the extension works, besides UI Issues in the Admin section, there won't be a new version.
