### ISSUE TITLE
Invalid Token error during token-exchange

### ISSUE THREAD

**Issue by omar-diop** [klausbetz/apple-identity-provider-keycloak#53]
Hello and thanks for the work that you have done!

I'm opening this issue because I'm stuck with the web implementation of Sign in with Apple.
I've correctly installed the provider and configured as your documentation says:

<img width="602" alt="Screenshot 2023-09-11 alle 17 55 59" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/3faffdc7-1ff9-49ed-b93a-a38eb7607f50">

<img width="1054" alt="Screenshot 2023-09-11 alle 17 52 22" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/cdfb9762-a70d-40c4-89ae-14bb673e48a1">

<img width="1264" alt="Screenshot 2023-09-11 alle 17 54 44" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/63066e73-4e5e-478d-8b04-642e1441acce">

<img width="1272" alt="Screenshot 2023-09-11 alle 17 54 56" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/fc58346e-89ae-4197-b439-8ebec1954c79">

<img width="1148" alt="Screenshot 2023-09-11 alle 17 55 26" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/5bc96118-3235-4521-8d14-2bf20dede493">

On Apple Developer is all configured (ServiceID, Key, Redirect Urls etc)

Currently my flow is:

**1. The web application calls Keycloak's `/protocol/openid-connect/auth` endpoint that generates the following url**

`https://identity-staging.learnn.com/realms/learnn/protocol/openid-connect/auth?client_id=learnn-web&redirect_uri=https://my-staging.learnn.com/login&response_type=code&scope=openid+profile+email+self&kc_idp_hint=apple&nonce=1694448024810`

https://my-staging.learnn.com is my website's url where at the end i perform the token-exchange call

**2. The web application opens the generated url**
The url redirects to Apple's url where i perform a login.

`https://appleid.apple.com/auth/authorize?response_mode=form_post&scope=openid+name%20email&state=hKnRMRJ1bOE0iLfuS_H4-OkamQHZQsrNvsHXSAVqQwI.z1-bo9b5Aow.BtOpOk_IQNetZ8YhNcsV_w&response_type=code&client_id=com.learnn.apple&redirect_uri=https%3A%2F%2Fidentity-staging.learnn.com%2Frealms%2Flearnn%2Fbroker%2Fapple%2Fendpoint&nonce=5RjVyw1VRSP8DlzLDQoPFQ`

**3. After the login user is redirected to the web application with ?code as querystring parameter**
<img width="1489" alt="image" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/1e714772-5b6f-4003-9067-580798819d0a">

**4. I use this code to follow your ["Using apple authorization_code flow"](https://github.com/klausbetz/apple-identity-provider-keycloak#2-using-apple-authorization_code) and i call /protocol/openid-connect/token endpoint**

`https://identity-staging.learnn.com/realms/learnn/protocol/openid-connect/token`

<img width="685" alt="Screenshot 2023-09-11 alle 18 13 15" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/50a2fc66-0064-4637-9bb1-c1cca3c6032e">

This call ends with this error
`{"error":"invalid_token","error_description":"Invalid token"}`
<img width="488" alt="image" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/69193592/575406b6-0755-4859-b4c9-a230cfaf179d">

I'm stuck here, I've tested a lot of different configurations without success, I've some questions for you:

1. I didn't use [Apple ID Token flow](https://identity-staging.learnn.com/realms/learnn/protocol/openid-connect/token) because i couldn't find it in my querystrings parameters, how can i retrieve that id_token?

2. I tried to pass id_token in /protocol/openid-connect/auth call as `response_type=code id_token` and when i get redirected to my webapp i have an id_token in querystring but when i decoded it i discovered that was a Keycloak token containing all the user info. Does the plugin automatically perform token exchange without the need to manually call /token endpoint ?

Thanks a lot!

**Comment by mirko-pira** [comment]
@omar-diop based on what you've described, it's plausible that Keycloak is already handling the token exchange for you when you're redirected back to your application with an authorization code.

Typically, OpenID Connect (OIDC) providers like Keycloak perform token exchange internally when the service redirects back to the client application with an authorization code. The code is intended to be exchanged for a token set (ID Token, Access Token, possibly a Refresh Token) by the server-side component of your application. However, if you're directly interacting with Keycloak's OIDC endpoints, this might already be taken care of.

If you are seeing an id_token in the query string and it appears to be a Keycloak token containing the user information, then it's highly likely that the token exchange is being performed by Keycloak automatically. In this case, you may not need to perform the token exchange manually.

That said, these are educated guesses based on typical OIDC and Keycloak behavior. The configuration settings and the exact flow can vary. I would recommend confirming this behavior with @klausbetz, to make sure you're on the right track.

As for your question about retrieving the Apple id_token, you generally only get the id_token if you explicitly ask for it during the initial authorization request to Apple, and if the user successfully logs in. However, given that Keycloak is in between your application and Apple, Keycloak might be the one processing this id_token and transforming it into its own token set that you later receive.

I hope this helps clarify your situation and maybe is required to update the README.

Your process should be:
1. call /auth (Keycloak)
2. external sign in with apple
3. redirect in your application with the "code" in the params
4. call /token (Keycloak) with the authorization_code in step 3
5. receive "access_token"

**Comment by klausbetz** [comment]
@omar-diop Thx for raising your issue.

@mirko-pira's explanation is accurate.

I've a few things to add, as it seems to be confusing when to use token-exchange.

1. As long as the whole login flow happens in the browser there's no need for token-exchange. It happens automatically.
    - The whole login flow includes navigating to the Keycloak-Login page, getting forwarded to Apple, getting redirected back to Keycloak, and then back to your application
2. Only when your native iOS/macOS application requests an `authorization_code` directly from Apple without Keycloak in the middle a token-exchange is required.
    - When requesting the `authorization_code` directly from Apple, you usually get the ID-Token next to the `authorization_code` in the response from Apple (but make sure to request `name` and/or `email` scope from Apple).

**Comment by omar-diop** [comment]
@mirko-pira @klausbetz thanks for the replies, we managed to fix our issue without using token exchange 🙂

@klausbetz if you want we can make a PR to extend the documentation explaining when token exchange is needed.

**Comment by klausbetz** [comment]
@omar-diop Great news! Feel free to create a PR. Any contribution is very much appreciated 😄
