### ISSUE TITLE
Apple Phone provider for keycloak 21.0.2 version

### ISSUE THREAD

**Issue by htaimoor2010** [klausbetz/apple-identity-provider-keycloak#55]
Hi,
I am using keycloak phone provider extension so that user is able to login into the system through OTP and stuff. I want to integrate this apple-identity-provider-keycloak extension into it. The issue is that this keycloak version that it is using(21.0.2) doesnot have the keyId, teamId and other configs on the admin UI. How can I do all these settings to make it work?

I passed the clientId and clientSecret from UI and it threw the following exception
![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/59606586/39610cef-dfe1-4312-bc58-d673239a4425)

**2023-10-06 07:34:37,570 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-14) Uncaught server error: org.jboss.resteasy.spi.InternalServerErrorException: RESTEASY003815: Subresource for target class has n
o jax-rs annotations.: at.klausbetz.provider.AppleIdentityProviderEndpoint**

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/59606586/7834c43c-282e-41f5-9705-4bb8804992c3)

**Comment by klausbetz** [comment]
Yeah.

Keycloak 21's UI doesn't support external social provider plugins like this one.

The easiest thing you can do to use the UI for configuration, is to update to Keycloak 22.

If you cannot upgrade, then you could use external configuration tools like keycloak-config-cli or you modify the values in the database (`identity_provider_config` table) directly:
<img width="829" alt="Bildschirmfoto 2023-10-06 um 09 56 31" src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/78362353/6ced82b4-d896-4959-b5b9-c731e61359c5">

**Comment by htaimoor2010** [comment]
Is there any way to pass keyId,teamId and other related configs in params like these? It would be of great help if  possible.

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/59606586/edf2dee5-8f07-40b5-a67a-e9acbef5e60f)

**Comment by klausbetz** [comment]
**Short answer**  
I don't think so.

**Long answer**. 
Your config looks like a global Keycloak configuration. As the Apple Identity Provider doesn't work globally for the whole instance, but per realm, I don't think you can achieve it like you did it in your screenshot.

**Comment by htaimoor2010** [comment]
worked like a charm after updating to Keycloak 22! Thanks
