### ISSUE TITLE
Context null pointer Exception

### ISSUE THREAD

**Issue by tungboom** [klausbetz/apple-identity-provider-keycloak#56]
I am using keycloak version 21.0.2 and apple provider version 1.5.0.

An error occurred while callback from Apple login page. This is the log:
![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/5f87217f-1c49-4754-8a6c-80d09ec37121)

I have updated more information in the database
![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/d0ff20ee-7970-4b67-8c12-aced5dd19e5d)

Thanks!

**Comment by klausbetz** [comment]
Hi @tungboom,

Thank you, for raising this issue. Welcome to the open source world 😁 

Do you have any chance to update to Keycloak 22? `21.X.Y` is a real nightmare for extensions.


Anyways, the clientId looks suspicious to me. Usually, the clientId looks like `com.example.yourapp` instead of `com-example-yourapp`.

**Comment by tungboom** [comment]
Hi @klausbetz ,

Thanks for your response.

I replaced com-example-yourapp to com.example.yourapp but it still doesn't work.

Anyway, I can't upgrade to keycloak 22 because I'm using the provider: https://github.com/cooperlyt/keycloak-phone-provider.
It is only supporting keycloak 21.X.Y.

Do you have another solution?

**Comment by tungboom** [comment]
I tried upgrading to keycloak 22.0.1 + provider ver 1.7.1 and still get the same error

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/cb3b3975-2cdb-4aaa-84a5-732cfb10a96c)

**Comment by klausbetz** [comment]
I see. Thx for trying to upgrade to v22.

Since you have a p8 Key, I assume you should have a Service ID (=clientId) from Apple as well?  
Is `<whatever>.staging` (clientId of your screenshot) the Service ID from your App/Service in your Apple Developer Account? You may want to check with this [guide](https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#how-sign-in-with-apple-works-hint-it-uses-oauth-and-oidc)

**Comment by tungboom** [comment]
This is a screenshots:

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/e23b9f94-5e44-4784-bbc1-3458dd059fc9)

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/771f321f-c531-4654-927b-25876f3c6169)

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/8e3ba210-2d45-4eee-a683-00b1c6080fc1)

**Comment by klausbetz** [comment]
Hmmm... That's a tough one. I cannot see any obvious misconfiguration.

Still, the error from Apple `invalid_client` indicates there's some misconfiguration.

How do you perform the login?
- completely in the browser?
- or are you on an iOS/macOS device and request an ID/Authorization Token yourself using Apple's SDK? (then a token-exchange is necessary to complete the login)

**Comment by tungboom** [comment]
I log in using a browser.

Do I need to configure anything else here?

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/f4ed49ec-7173-4e6b-bf7a-1b3cb2bada48)

**Comment by tungboom** [comment]
I have set the log in the provider and found the information is correct.

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/175fc9cc-e8cc-4481-8bb6-28686c3d51a2)

So the error here is that calling apple's api https://appleid.apple.com/auth/token returns status 400

**Comment by tungboom** [comment]
Is it caused by generating ClientSecret?

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/1fc5325c-7c5e-4433-acc9-49d1cc2d5a89)

**Comment by tungboom** [comment]
@klausbetz Thanks for your help. I have generated client secret using ruby and it works.
Please close this issue.

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/23371853/d70e4ffb-9f2c-4157-a35c-f20fc364438c)

**Comment by klausbetz** [comment]
@tungboom That's interesting. How does your setup look like? Does Keycloak run in a Docker container or did you install it directly on your Mac/Windows/Linux machine?

**Comment by tungboom** [comment]
@klausbetz I run in a Docker container and k8s

**Comment by klausbetz** [comment]
Ok. thx. I'll keep that in mind and may investigate it further, if this occurs more often.
