### ISSUE TITLE
Internal server error after upgrading to KeyCloak v23.0.1

### ISSUE THREAD

**Issue by jwesselink** [klausbetz/apple-identity-provider-keycloak#60]
After upgrading from v22.0.5 to v23.0.1, I get an Internal server error after being redirected back to KeyCloak.

I'm not seeing any error logs in the console logging.

Is there anything I can do to get more info to help you?

**Comment by klausbetz** [comment]
Hi @jwesselink,

I'm sorry for responding that late.
I'll try to reproduce it on my setup.

Just for clarification: Your setup worked fine with `v22.0.5`?

**Comment by kotofey-da-powah** [comment]
Problem seems to be resolved with `v23.0.3` and `1.8.0`. Can you double-check this on your setup?

**Comment by klausbetz** [comment]
Tested using `1.8.0` and Keycloak `v23.0.0`, `v23.0.2` and `v23.0.3`.
Unfortunately, all versions of Keycloak behave the same. :/

**Comment by jwesselink** [comment]
v23.0.3 and 1.8.0 still fails with internal server error after being redirect back

**Comment by klausbetz** [comment]
@jwesselink: Thank you for investigating and fixing this issue!
You just made this extension better than it was before 🙇 

Please check out [1.9.0](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.9.0).
