### ISSUE TITLE
Apple sing in from WKWebview not working after iOS 17.1.2 update

### ISSUE THREAD

**Issue by Sonym2** [klausbetz/apple-identity-provider-keycloak#61]
Hi everyone,

until iOS update 17.1.2 all worked great.

From 17.1.2 if you open KC login page in webview, and hit the apple login button, native apple sign in sheet doesn't appear and you are redirected to url 

`https://appleid.apple.com/auth/authorize?response_mode=form_post&scope=openid+name%20email&state=ovZJhHDLihEVVz03Z8Y9HTe64auGkMEgI_K3oLZKbek.ykSmwrwBSmY.7-9LxzvWQBSL35RtLu85-Q&response_type=code&client_id=****&redirect_uri=****&nonce=h-KZoVDVmedOPIujLP-Mdw`

<img src="https://github.com/klausbetz/apple-identity-provider-keycloak/assets/11892079/b3eb958b-0bcd-4012-95f8-9d130e54c3d9"  width="200">

If you open Keycloak login page in external browser like Safari, it works great as before.

So my question is, did Apple restrict use of apple sign in from webviews? Is there any other way how to get tokens from keycloak from native ios app using native appleid sign. 

Thanks for help

**Comment by klausbetz** [comment]
I can't tell if Apple changed a thing here. However, it's suspicious that from iOS 17.1.2 on the native dialog won't open any longer...

Sure, there's a different way of dealing with native sign in.
That's where [token-exchange](https://github.com/klausbetz/apple-identity-provider-keycloak#token-exchange) comes in. You could use native Apple Sign In SDK to retrieve an ID-Token. The ID-Token can then be sent to Keycloak to be exchanged for access/refresh_token.

**Comment by Sonym2** [comment]
It seems it works again from 17.2 update.
