### ISSUE TITLE
Redirected to Keycloak login form after cancelling the login with Apple

### ISSUE THREAD

**Issue by LuisPintoIt** [klausbetz/apple-identity-provider-keycloak#62]
Hello,

I'm encountering the following problem:

After clicking the cancel button, as shown in the screenshot below:
![Screenshot from 2023-12-13 12-17-32](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/153730269/bea5dba7-4b6d-4330-9552-c50572ead053)

I am being redirected to the Keycloak Login form, and the only message I receive in the logs is user_cancelled_authorize for broker login apple. There are no other events or actions taking place.

In accordance with my specific requirements, I need to terminate the entire page and prevent redirection to the Keycloak login form. If it's possible, I would greatly appreciate it if you could send a Keycloak event that I can capture using Keycloak SPI and handle the page termination myself.

**Comment by klausbetz** [comment]
Hi @LuisPintoIt,
Sounds like a missing thing in the extension. I'll add an event when the user cancels the login 👍

**Comment by klausbetz** [comment]
Pls check [1.8.0](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.8.0) if that's sufficient for your use case.
Feel free to create a PR in case you want to add something.

This is what the event looks like:  
`2023-12-15 15:57:42,019 WARN  [org.keycloak.events] (executor-thread-7) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=skeleton, clientId=account-console, userId=null, ipAddress=<ip>, error=identity_provider_login_failure, idp=apple, code_id=<code>`

**Comment by klausbetz** [comment]
Closing, due to inactivity.
