### ISSUE TITLE
User Session Note Mapper for Apple IdP not available

### ISSUE THREAD

**Issue by alexanderhofstaetter** [klausbetz/apple-identity-provider-keycloak#72]
we need to map attributes from the appleid id_token to the user session note via the pedifened "User Session Note Mapper" known from other IdPs is not available.

however in an apple IdP the "User Session Note Mapper" is NOT available.

See other IdPs:

![image](https://github.com/klausbetz/apple-identity-provider-keycloak/assets/6820505/5d1f88ee-7ad9-4af9-8125-ca6208ad0cda)

also some other mappers are missing

**Comment by klausbetz** [comment]
Hallo ;)

thx for creating this issue.
I'll compare the mappers to the Google Provider and move from there.

**Comment by klausbetz** [comment]
I found that almost all the other social providers do not have all available mappers installed. There might be a reason for that. 

Anyways, could you please try this version of the Apple extension and let me know if it works for you? I'll release a new version then.
[apple-identity-provider-1.11.0-alpha.jar.zip](https://github.com/user-attachments/files/15537062/apple-identity-provider-1.11.0-alpha.jar.zip)

**Comment by alexanderhofstaetter** [comment]
Perfect! I tested It and session attributes / imports now works and it solves our problem! Thank you! Seems good
