### ISSUE TITLE
idp display name not available

### ISSUE THREAD

**Issue by alexanderhofstaetter** [klausbetz/apple-identity-provider-keycloak#73]
the display name config field is not available. one there cannot change the name od the apple idp

**Comment by klausbetz** [comment]
True that.

The Apple extension behaves the same way as all the other social providers do. The name is hardcoded so to say.
I'll provide another alpha version soon

**Comment by klausbetz** [comment]
In any case: If you need to support multiple languages you might consider overriding the Apple-Login button in your login theme anyways, as you can only define one text in the admin ui.

**Comment by klausbetz** [comment]
The displayname is editable in the [latest release](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.11.0)
