### ISSUE TITLE
Not compatible with KC25 ? (NoSuchMethodError: setIdpConfig)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [klausbetz/apple-identity-provider-keycloak#82]
**Describe the bug**
"Internal Server Error" while login with apple IdP on KC 25.0.1

**`Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.broker.provider.BrokeredIdentityContext.setIdpConfig(org.keycloak.models.IdentityProviderModel)'`**

<details>

<summary>Keycloak Logs (turn log-level to DEBUG)</summary>

```plaintext
keycloaktest     | 2024-06-29 11:40:00,388 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-15) Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.broker.provider.BrokeredIdentityContext.setIdpConfig(org.keycloak.models.IdentityProviderModel)'
keycloaktest     | 	at at.klausbetz.provider.AppleIdentityProvider.sendTokenRequest(AppleIdentityProvider.java:120)
keycloaktest     | 	at at.klausbetz.provider.AppleIdentityProviderEndpoint.authResponse(AppleIdentityProviderEndpoint.java:80)
keycloaktest     | 	at at.klausbetz.provider.AppleIdentityProviderEndpoint$quarkusrestinvoker$authResponse_4fc13bf1eac39a8362cbed0bd45aab97fb8a03f4.invoke(Unknown Source)
keycloaktest     | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloaktest     | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloaktest     | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloaktest     | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloaktest     | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloaktest     | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloaktest     | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloaktest     | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloaktest     | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloaktest     | 	at java.base/java.lang.Thread.run(Thread.java:1583)

```

</details>

**Comment by klausbetz** [comment]
Hi @alexanderhofstaetter 

thx for creating this issue.
Please try to update the extension you're using to [v1.13.0](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.13.0).

**Comment by patrickmichalina** [comment]
I am also having issues. There is a "flash" after logging in on web browsers. Like the consent screen is no longer being displayed. However, it works on iOS devices with the native lower toast that does the apple id flow.

**Comment by klausbetz** [comment]
Just tested it using v1.13.0 and Keycloak v25.0.1. No issues detected so far.
@patrickmichalina Could you please clarify what you mean by consent screen is not displayed?

**Comment by alexanderhofstaetter** [comment]
Works for us, we indeed had a wrong (old) version for the plugin. Sorry & thanks!

**Comment by patrickmichalina** [comment]
@klausbetz sorry, it was actually a chrome ad-blocker that was quickly removing the div from the consent screen. Very strange behavior. Disregard my previous complaint. Cheers!

**Comment by klausbetz** [comment]
@patrickmichalina: Great to hear! No worries.
