### ISSUE TITLE
Advertise extension on keycloak.org

### ISSUE THREAD

**Issue by stianst** [klausbetz/apple-identity-provider-keycloak#9]
If there is interest in it, it would be great to see this extension listed on https://www.keycloak.org/extensions.html

A simple PR to https://github.com/keycloak/keycloak-web/tree/main/extensions is all that is needed to do that. I would prefer the PR comes from one of the maintainers of this repository though.

@klausbetz :)

**Comment by klausbetz** [comment]
Thx for this great idea @stianst :grin:
Will definitely do it.

**Comment by klausbetz** [comment]
Created PR https://github.com/keycloak/keycloak-web/pull/338

**Comment by stianst** [comment]
Thanks
